### ISSUE TITLE
Space in link destination generates IndexError

### ISSUE THREAD

**Issue by mib112** [executablebooks/markdown-it-py#205]
### Describe the bug

A space character right after a link destination scheme causes an IndexError.

```markdown
[Contact](http:// mail.com)
[Contact](mailto: mail@mail.com)
```

### Reproduce the bug

```python
from markdown_it import MarkdownIt
MarkdownIt().parse("[Contact](mailto: mail@mail.com)")
```

**Error**

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/main.py", line 260, in parse
    self.core.process(state)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/parser_core.py", line 33, in process
    rule(state)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/rules_core/inline.py", line 10, in inline
    state.md.inline.parse(token.content, state.md, state.env, token.children)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/parser_inline.py", line 120, in parse
    self.tokenize(state)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/parser_inline.py", line 102, in tokenize
    ok = rule(state, False)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/rules_inline/link.py", line 54, in link
    href = state.md.normalizeLink(res.str)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/main.py", line 331, in normalizeLink
    return normalize_url.normalizeLink(url)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/markdown_it/common/normalize_url.py", line 21, in normalizeLink
    parsed = mdurl.parse(url, slashes_denote_host=True)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/mdurl/_parse.py", line 300, in url_parse
    u.parse(url, slashes_denote_host)
  File "/Library/Caches/pypoetry/virtualenvs/webapp-gmQ5g8dx-py3.9/lib/python3.9/site-packages/mdurl/_parse.py", line 204, in parse
    if rest[host_end - 1] == ":":
IndexError: string index out of range
```

### List your environment

Python 3.9
markdown-it-py 2.0.1

**Comment by MoritzGiessmann** [comment]
I have the same issue.

**Comment by markusbrunner-design** [comment]
Happens for me, too...

**Comment by mib112** [comment]
Completely missing host is also causing an index error:

`[Contact](http://)`

**Comment by chrisjsewell** [comment]
Oh absolutely @markusbrunner-design; I'm not saying that it won't get fixed, just noting that the fix will still not parse it as a link, in case this is what anyone is expecting

**Comment by hukkin** [comment]
I also don't have the time to look into this right now, but I'd expect the fix to be primarily needed in markdown-it-py, not mdurl. I expect this because as mentioned, there is no valid link, so I'd expect `mdurl.parse` not to be called in the first place.

I'd probably approach this by seeing what Javascript markdown-it does with the same input and whether or not it callls mdurl.

**Comment by mib112** [comment]
@hukkin your assumption seems to be correct. Javascript markdown-it renders

```
[Contact](http:// mail.com)

[Contact](mailto: mail@mail.com)
```

to 

```
<p>[Contact](http:// <a href="http://mail.com">mail.com</a>)</p>
<p>[Contact](mailto: <a href="mailto:mail@mail.com">mail@mail.com</a>)</p>
```

which does not recognize the input as a markdown link, but does GFM-style autolinking.

(Nevertheless, I would think that [index access in mdurl parse](https://github.com/executablebooks/mdurl/blob/master/src/mdurl/_parse.py#L205) behaves differently in python than in javascript, since a negative index results in an error in python, while in javascript the result is undefined.)

**Comment by mib112** [comment]
Further investigation shows that markdown-it passes "http://" to mdurl. The javascript version actually handles the parsing of "http://" differently, then. By the fact that a negative index in javascript really does not generate an error, you get as parsing result:

`url {protocol: 'http:', slashes: true, auth: null, port: null, hostname: '', pathname: null, search: null, hash: null}`

In further processing this result is rejected as valid link (hostname must not be '').

I can provide a PR for mdurl which mimics the javascript behavior ...

**Comment by hukkin** [comment]
Awesome, thanks for the PRs!

I've released `mdurl==0.1.1` which should fix this.

**Comment by chrisjsewell** [comment]
🎉  cheeers @hukkin

**Comment by chrisjsewell** [comment]
and cheers @mib112, with the update to mdurl and test in place, I guess we can close this

**Comment by ptrcnull** [comment]
Hi, this doesn't seem to be solved..

```
>           if rest[host_end - 1] == ":":
E           IndexError: string index out of range

/usr/lib/python3.10/site-packages/mdurl/_parse.py:204: IndexError
=================================== short test summary info ===================================
FAILED tests/test_port/test_fixtures.py::test_commonmark_extras[667-Issue #205.  Space in link destination generates IndexError-[Contact](http:// mail.com)\n\n[Contact](mailto: mail@mail.com)\n-<p>[Contact](http:// mail.com)</p>\n<p>[Contact](mailto: mail@mail.com)</p>\n]
======================== 1 failed, 851 passed, 18 deselected in 2.80s =========================
```

<details>
<summary>Full tests output</summary>

```
========================================== FAILURES ===========================================
_ test_commonmark_extras[667-Issue #205.  Space in link destination generates IndexError-[Contact](http:// mail.com)\n\n[Contact](mailto: mail@mail.com)\n-<p>[Contact](http:// mail.com)</p>\n<p>[Contact](mailto: mail@mail.com)</p>\n] _

line = 667, title = 'Issue #205.  Space in link destination generates IndexError'
input = '[Contact](http:// mail.com)\n\n[Contact](mailto: mail@mail.com)\n'
expected = '<p>[Contact](http:// mail.com)</p>\n<p>[Contact](mailto: mail@mail.com)</p>\n'

    @pytest.mark.parametrize(
        "line,title,input,expected",
        read_fixture_file(FIXTURE_PATH.joinpath("commonmark_extras.md")),
    )
    def test_commonmark_extras(line, title, input, expected):
        md = MarkdownIt("commonmark")
        md.options["langPrefix"] = ""
>       text = md.render(input)

tests/test_port/test_fixtures.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
markdown_it/main.py:267: in render
    return self.renderer.render(self.parse(src, env), self.options, env)
markdown_it/main.py:252: in parse
    self.core.process(state)
markdown_it/parser_core.py:32: in process
    rule(state)
markdown_it/rules_core/inline.py:10: in inline
    state.md.inline.parse(token.content, state.md, state.env, token.children)
markdown_it/parser_inline.py:120: in parse
    self.tokenize(state)
markdown_it/parser_inline.py:102: in tokenize
    ok = rule(state, False)
markdown_it/rules_inline/link.py:54: in link
    href = state.md.normalizeLink(res.str)
markdown_it/main.py:321: in normalizeLink
    return normalize_url.normalizeLink(url)
markdown_it/common/normalize_url.py:22: in normalizeLink
    parsed = mdurl.parse(url, slashes_denote_host=True)
/usr/lib/python3.10/site-packages/mdurl/_parse.py:300: in url_parse
    u.parse(url, slashes_denote_host)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <mdurl._parse.MutableURL object at 0x7fc4748d4670>, url = 'http://'
slashes_denote_host = True

    def parse(self, url: str, slashes_denote_host: bool) -> "MutableURL":
        lower_proto = ""
        slashes = False
        rest = url
    
        # trim before proceeding.
        # This is to support parse stuff like "  http://foo.com  \n"
        rest = rest.strip()
    
        if not slashes_denote_host and len(url.split("#")) == 1:
            # Try fast path regexp
            simple_path = SIMPLE_PATH_PATTERN.match(rest)
            if simple_path:
                self.pathname = simple_path.group(1)
                if simple_path.group(2):
                    self.search = simple_path.group(2)
                return self
    
        proto = ""
        proto_match = PROTOCOL_PATTERN.match(rest)
        if proto_match:
            proto = proto_match.group()
            lower_proto = proto.lower()
            self.protocol = proto
            rest = rest[len(proto) :]
    
        # figure out if it's got a host
        # user@server is *always* interpreted as a hostname, and url
        # resolution will treat //foo/bar as host=foo,path=bar because that's
        # how the browser resolves relative URLs.
        if slashes_denote_host or proto or re.search(r"^//[^@/]+@[^@/]+", rest):
            slashes = rest.startswith("//")
            if slashes and not (proto and HOSTLESS_PROTOCOL[proto]):
                rest = rest[2:]
                self.slashes = True
    
        if not HOSTLESS_PROTOCOL[proto] and (
            slashes or (proto and not SLASHED_PROTOCOL[proto])
        ):
    
            # there's a hostname.
            # the first instance of /, ?, ;, or # ends the host.
            #
            # If there is an @ in the hostname, then non-host chars *are* allowed
            # to the left of the last @ sign, unless some host-ending character
            # comes *before* the @-sign.
            # URLs are obnoxious.
            #
            # ex:
            # http://a@b@c/ => user:a@b host:c
            # http://a@b?@c => user:a host:c path:/?@c
    
            # v0.12 TODO(isaacs): This is not quite how Chrome does things.
            # Review our test case against browsers more comprehensively.
    
            # find the first instance of any hostEndingChars
            host_end = -1
            for i in range(len(HOST_ENDING_CHARS)):
                hec = rest.find(HOST_ENDING_CHARS[i])
                if hec != -1 and (host_end == -1 or hec < host_end):
                    host_end = hec
    
            # at this point, either we have an explicit point where the
            # auth portion cannot go past, or the last @ char is the decider.
            if host_end == -1:
                # atSign can be anywhere.
                at_sign = rest.rfind("@")
            else:
                # atSign must be in auth portion.
                # http://a@b/c@d => host:b auth:a path:/c@d
                at_sign = rest.rfind("@", 0, host_end + 1)
    
            # Now we have a portion which is definitely the auth.
            # Pull that off.
            if at_sign != -1:
                auth = rest[:at_sign]
                rest = rest[at_sign + 1 :]
                self.auth = auth
    
            # the host is the remaining to the left of the first non-host char
            host_end = -1
            for i in range(len(NON_HOST_CHARS)):
                hec = rest.find(NON_HOST_CHARS[i])
                if hec != -1 and (host_end == -1 or hec < host_end):
                    host_end = hec
            # if we still have not hit it, then the entire thing is a host.
            if host_end == -1:
                host_end = len(rest)
    
>           if rest[host_end - 1] == ":":
E           IndexError: string index out of range

/usr/lib/python3.10/site-packages/mdurl/_parse.py:204: IndexError
=================================== short test summary info ===================================
FAILED tests/test_port/test_fixtures.py::test_commonmark_extras[667-Issue #205.  Space in link destination generates IndexError-[Contact](http:// mail.com)\n\n[Contact](mailto: mail@mail.com)\n-<p>[Contact](http:// mail.com)</p>\n<p>[Contact](mailto: mail@mail.com)</p>\n]
======================== 1 failed, 851 passed, 18 deselected in 2.80s =========================
```
</details>
