### ISSUE TITLE
Exception with markdown file with ### as last line.

### ISSUE THREAD

**Issue by davidorme** [executablebooks/markdown-it-py#71]
The problem is that `jupyter-book` throws an exception when a markdown input file finishes on a line containing only `#` characters. The traceback is below, but the heart of it is that the `markdown_it` code to handle headers doesn't get a 2 tuple of header level and header text, just the header level.

This would be a shoddy careless thing to have in an input but - when I did it - it took me a long time to figure out what was going on! I don't know whether the fix is at `jupyter-book` level - I suspect it is more appropriate to get `markdown-it` to handle such idiocy more cleanly.

**To Reproduce**

```sh
# make a simple test from the template
jupyter-book create test
```
Now edit `test/markdown.md` to add a last line (_no_ new line) consisting of just `#` characters

```sh
# Try to build
jupyter-book build test
```

The exception traceback looks like this:

```
The full traceback has been saved in /var/folders/62/cz0ctby96lq7ggnytfbtd__40000gn/T/sphinx-err-krkewuhj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/jupyter_book/sphinx.py", line 141, in build_sphinx
    app.build(force_all, filenames)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/io.py", line 223, in read_doc
    pub.publish()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sphinx/io.py", line 128, in read
    self.parse()
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/myst_nb/parser.py", line 59, in parse
    super().parse(inputstring, document=document)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/myst_parser/sphinx_parser.py", line 187, in parse
    parser.render(inputstring)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/main.py", line 244, in render
    return self.renderer.render(self.parse(src, env), self.options, env)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/main.py", line 229, in parse
    self.core.process(state)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/parser_core.py", line 33, in process
    rule(state)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/rules_core/block.py", line 15, in block
    state.src, state.md, state.env, state.tokens, state.srcCharCode
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/parser_block.py", line 100, in parse
    self.tokenize(state, state.line, state.lineMax)
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/parser_block.py", line 77, in tokenize
    if rule(state, line, endLine, False):
  File "/Users/dorme/.pyenv/versions/3.7.7/lib/python3.7/site-packages/markdown_it/rules_block/heading.py", line 35, in heading
    ch = state.srcCharCode[pos]
IndexError: list index out of range
```

**Comment by davidorme** [comment]
@choldgraf, exactly. Embarrassed as I am to admit it. There should be penalties but that traceback is a harsh one.

**Comment by chrisjsewell** [comment]
lol no worries
