### ISSUE TITLE
UnicodeError with some HTML entities 

### ISSUE THREAD

**Issue by lesteve** [executablebooks/markdown-it-py#80]
**Describe the bug**

There is a rendering issue with some HTML entities for example this one `&#x1F4AC;` which is 💬 (speech balloon according to https://graphemica.com/%F0%9F%92%AC), creates a HTML string that can not be encoded in UTF8. This causes a hard to understand `UnicodeError` in JupyterBook.

For completeness the work-around of copying and pasting 💬 into my editor worked, unfortunately this was not the first thing I tried :sweat: ...

**To Reproduce**

```py
from markdown_it import MarkdownIt

md = MarkdownIt()

text = ("&#x1F4AC;")
html = md.render(text)
html.encode('utf8')
```

yields the error:
```
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-8-063cca89ac1a> in <module>
      5 text = ("&#x1F4AC;")
      6 html = md.render(text)
----> 7 html.encode('utf8')

UnicodeEncodeError: 'utf-8' codec can't encode characters in position 3-4: surrogates not allowed
```

**Expected behavior**

The HTML entity is rendered correctly, for example the Javascript markdown-it parser renders `&#x1F4AC;` fine: see [this](
https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%26%23x1F4AC%3B%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Additional context**

I was having the problem in JupyterBook when adding `&#x1F4AC;` into one of my `.md` file.

<details>

<summary>Full JupyterBook stack-trace</summary>

```
The full traceback has been saved in /tmp/sphinx-err-ssczzp1s.log, if you want to report the issue to the developers.
Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/jupyter_book/sphinx.py", line 141, in build_sphinx
    app.build(force_all, filenames)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 361, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 535, in write
    self._write_serial(sorted(docnames))
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 545, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 597, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/docutils/writers/__init__.py", line 79, in write
    output = self.destination.write(self.output)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/docutils/io.py", line 439, in write
    self.destination = self.encode(data)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/docutils/io.py", line 200, in encode
    return data.encode(self.encoding, self.error_handler)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 1903-1904: surrogates not allowed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 259, in build
    builder_specific_actions(
  File "/home/lesteve/miniconda3/envs/scikit-learn-tutorial/lib/python3.8/site-packages/jupyter_book/commands/__init__.py", line 500, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================
```

</details>

**Comment by hukkinj1** [comment]
Made a PR to fix this: https://github.com/executablebooks/markdown-it-py/pull/81
